services:
  app:
    build: .
    container_name: devops-demo-app
    ports:
      - "5000:5000"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: devops-demo-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - app
    restart: unless-stopped
